      PROGRAM FINDATA
C  THIS PROGRAM PREPARES A DATA FILE FOR THE PROGRAM FINELEM2 WHICH
C  GIVES A FINITE-ELEMENT SOLUTION OF THE PROBLEM OF A 
C  HEATED PLATE INSULATED ON ITS TOP AND BOTTOM SURFACES WITH ALL
C  ELEMENTS TRIANGULAR.   DIFFERENTIAL BOUNDARY CONDITIONS ARE
C  SPECIFIED BY     
C           CAPPA*(D(THETA)/D(N)) = -M*THETA + S
C  WHERE N IS ALONG THE DIRECTION OF THE NORMAL TO THE SURFACE.
C  VALUES OF M AND S ARE INPUT AND SO ARE ESTIMATED BEFORE THE
C  PROGRAM IS USED.  SOME NODES, USUALLY AT BOUNDARIES, CAN BE 
C  SPECIFIED AS HAVING FIXED TEMPERATURES.   THERE IS PROVISION FOR
C  AN EXTENDED SOURCE OF HEAT WHICH IS GIVEN BY A FUNCTION STATEMENT
C  Q(x,y).   IF SUCH A SOURCE IS PRESENT THEN THE USER MUST ENSURE 
C  THAT IT GIVES THE REQUIRED FORM OF HEATING.   THERE IS ALSO 
C  PROVISION FOR UP TO 9 POINT SOURCES WHICH MUST BE SITUATED AT NODES.  
      DIMENSION NDE(100,3),NEDGE(50,2),CAY(50),SS(50),NP(50),SPS(50)
      OPEN(UNIT=11,FILE='FINELEM.DAT')
C  INPUT CONDUCTIVITY OF THE PLATE      
      WRITE(6,'(''ENTER CONDUCTIVITY'')')
      READ(5,*)Q
      WRITE(11,*)Q
      IOUT=0
      WRITE(6,'(''INPUT NUMBER OF ELEMENTS AND NUMBER OF NODES'')')
      READ(5,*)K,L
      WRITE(11,*)K,L
      WRITE(6,'(''ENTER NODE NUMBERS ASSOCIATED WITH EACH ELEMENT'')')
      WRITE(6,'(''  '')')
      DO 1 I=1,K
      WRITE(6,100)I
  100 FORMAT(38H ENTER 3 NODE NUMBERS DEFINING ELEMENT,I2)
      READ(5,*)(NDE(I,J),J=1,3)
      WRITE(11,*)(NDE(I,J),J=1,3)
    1 CONTINUE    
      WRITE(6,'(''ENTER COORDINATES OF NODES'')')
      DO 2 I=1,L
      WRITE(6,200)I,I
  200 FORMAT(9H ENTER x[,I2,8H] AND y[,I2,1H])
      READ(5,*)Q,R
      WRITE(11,*)Q,R
    2 CONTINUE   
      WRITE(6,'(''ENTER NUMBER OF NODES WITH FIXED TEMPERATURES'')')
      READ(5,*)NFT
      WRITE(11,*)NFT
      IF(NFT.EQ.0)GOTO 5
      DO 4 I=1,NFT
      WRITE(6,'(''READ IN NODE NUMBER, FIXED TEMPERATURE'')')
      READ(5,*)K,Q
      WRITE(11,*)K,Q
    4 CONTINUE
    5 WRITE(6,'(''ENTER THE NUMBER OF POINT SOURCES'')')
      READ(5,*)K
      WRITE(11,*)K
      IF(K.EQ.0)GOTO 13
      DO 14 I=1,K
      WRITE(6,'(''GIVE NODE AND STRENGTH OF POINT SOURCE [W/M**3]'')')
      READ(5,*)NP(I),SPS(I)
      WRITE(11,*)NP(I),SPS(I)
   14 CONTINUE
   13 WRITE(6,'(''HOW MANY EDGES OF ELEMENTS HAVE BOUNDARY '')')
      WRITE(6,'(''CONDITIONS OF THE FORM '')')
      WRITE(6,'('' D(THETA)/D(N) = -M*THETA + S ?'')')    
      READ(5,*)NBC
      WRITE(11,*)NBC
      IF(NBC.EQ.0)GOTO 16
      DO 15 I=1,NBC
      WRITE(6,'(''READ IN THE EDGE AS THE TWO END NODES AND THE '')')
      WRITE(6,'(''VALUES OF M AND S'')')
      READ(5,*)NEDGE(I,1),NEDGE(I,2),CAY(I),SS(I)
      WRITE(11,*)NEDGE(I,1),NEDGE(I,2),CAY(I),SS(I)
   15 CONTINUE   
   16 CLOSE(11)
      STOP
      END


