      PROGRAM POLYWALK
C  THIS PROGRAMME FINDS THE AVERAGE DISTANCE BETWEEN THE ENDS OF A
C  POLYMER CHAIN CONFINED TO TWO DIMENSIONS UNDER THE CONDITION
C  THAT THE POLYMER IS NOT ALLOWED TO CROSS ITSELF.   THE POLYMER
C  UNITS CORRESPOND TO THE STEPS OF A RANDOM WALK AND A MODIFIED
C  RANDOM WALK IS CARRIED OUT WHERE STEPS ARE ONLY IN THE X OR Y
C  DIRECTIONS.  A STEP IN A TRIAL THAT PRODUCES A CROSSED CHAIN IS
C  REPEATED UP TO FOUR TIMES TO FIND A NON-CROSSING PATH BUT IF IT 
C  DOES NOT DO SO THEN IT IS ABANDONNED AND THE RMS WALK IS CALCULATED
C  FROM THOSE THAT SUCCEED.   THE LENGTH OF CHAIN SHOULD BE RESTRICTED 
C  TO 50.
C
C  FOR THIS PROGRAMME A RANDOM NUMBER GENERATOR IS USED WHICH 
C  IS DERIVED FROM "NUMERICAL RECIPES" BY W.H. PRESS, B.P. FLANNERY,     
C  S.A. TEULKOLSKY AND W.T. VETTERLING (C.U.P.)
C
      DIMENSION LINKTAB(-40:40,-40:40),IPOS(2)
      DATA IDUM/-122/
      WRITE(6,'('' INPUT THE LENGTH OF THE CHAIN '')')
      READ(5,*)N
C  START THE 1000 TRIALS
      NSUM=0
      SUMD=0
      DO 2 I=1,1000
C  CLEAR LINKTAB
      DO 1 K=-40,40
      DO 1 L=-40,40
      LINKTAB(K,L)=0
    1 CONTINUE
C  THE FIRST STEP IS TAKEN ARBITRARILY IN THE +X DIRECTION
      LINKTAB(0,0)=1
      LINKTAB(1,0)=1
      IPOS(1)=1
      IPOS(2)=0
      DO 3 J=1,N-1
      ITRY=0
   13 ITRY=ITRY+1
      IF(ITRY.GT.4)GOTO 2
      R=RAN2(IDUM)
      IF(0.25.GE.R)GOTO 4
      IF(0.5.GE.R)GOTO 5
      IF(0.75.GE.R)GOTO 6
C  THE STEP IS ALONG +Y
      IPOS(2)=IPOS(2)+1
C  TEST TO SEE IF A CROSSING IS BEING MADE
      IF(LINKTAB(IPOS(1),IPOS(2)).EQ.1)GOTO 13
      LINKTAB(IPOS(1),IPOS(2))=1
      GOTO 3
C  THE STEP IS ALONG -Y
    6 IPOS(2)=IPOS(2)-1
C  TEST TO SEE IF A CROSSING IS BEING MADE
      IF(LINKTAB(IPOS(1),IPOS(2)).EQ.1)GOTO 13
      LINKTAB(IPOS(1),IPOS(2))=1
      GOTO 3
C  THE STEP IS ALONG +X
    5 IPOS(1)=IPOS(1)+1
C  TEST TO SEE IF A CROSSING IS BEING MADE
      IF(LINKTAB(IPOS(1),IPOS(2)).EQ.1)GOTO 13
      LINKTAB(IPOS(1),IPOS(2))=1
      GOTO 3
C  THE STEP IS ALONG -X
    4 IPOS(1)=IPOS(1)-1
C  TEST TO SEE IF A CROSSING IS BEING MADE
      IF(LINKTAB(IPOS(1),IPOS(2)).EQ.1)GOTO 13
      LINKTAB(IPOS(1),IPOS(2))=1
    3 CONTINUE
      SUMD=SUMD+FLOAT(IPOS(1))**2+FLOAT(IPOS(2))**2
      NSUM=NSUM+1
    2 CONTINUE
      WRITE(6,100)NSUM
  100 FORMAT(35H THE NUMBER OF SUCCESSFUL WALKS WAS,I4)
      RMS=SQRT(SUMD/NSUM)
      WRITE(6,200)RMS
  200 FORMAT(20H THE RMS DISTANCE IS,F9.2)
      STOP
      END           
                  
      FUNCTION RAN2(IDUM)
      PARAMETER(M=714025,IA=1366,IC=150889,RM=1./M)
      DIMENSION IR(97)
      DATA IFF/0/
      IF(IDUM.LT.0.OR.IFF.EQ.0)THEN
      IFF=1
      IDUM=MOD(IC-IDUM,M)
      DO 11 J=1,97
      IDUM=MOD(IA*IDUM+IC,M)
      IR(J)=IDUM
   11 CONTINUE
      IDUM=MOD(IA*IDUM+IC,M)
      IY=IDUM
      ENDIF
      J=1+(97*IY)/M
      IF(J.GT.97.OR.J.LT.1)PAUSE
      IY=IR(J)
      RAN2=IY*RM
      IDUM=MOD(IA*IDUM+IC,M)
      IR(J)=IDUM
      RETURN
      END

