      SUBROUTINE TRIDIAG(A,C,Y,N)
C  THIS PROGRAMME SOLVES A SET OF LINEAR EQUATIONS Ay = c WHERE
C  A IS A TRIDIAGONAL MATRIX.
C  THE PARAMETER MAX SETS THE MAXIMUM NUMBER OF EQUATIONS.
      PARAMETER (MAX=200)
      REAL WORK(MAX),A(3,N),C(N),Y(N)
C  FORWARD SUBSTITUTION
      DIV=A(2,1)
      IF(ABS(DIV).LT.1.0E-16)GOTO 50
      Y(1)=C(1)/DIV
      DO 1 I=2,N
      WORK(I)=A(3,I-1)/DIV
      DIV=A(2,I)-A(1,I)*WORK(I)
      IF(ABS(DIV).LT.1.0E-16)GOTO 50
      Y(I)=(C(I)-A(1,I)*Y(I-1))/DIV
    1 CONTINUE
C  BACK SUBSTITUTION
      DO 2 I=N-1,1,-1
      Y(I)=Y(I)-WORK(I+1)*Y(I+1)
    2 CONTINUE
      GOTO 60
   50 WRITE(6,'('' THE TRIDIAGONAL ALGORITHM HAS NOT WORKED BECAUSE'')')
      WRITE(6,'('' IT HAS DEVELOPED A ZERO DIVISOR. SINCE REALISTIC'')')
      WRITE(6,'('' PHYSICAL PROBLEMS SHOULD HAVE SOLUTIONS THIS IS '')')
      WRITE(6,'('' UNEXPECTED.    CHECK THE MAIN PROGRAMME.'')')
      STOP
   60 RETURN
      END        
